#define USER_PLUGIN_APB_BASE_ADDR 0x00

#define UP_APB_REG_CTRL   ( USER_PLUGIN_APB_BASE_ADDR + 0x0C )
#define UP_APB_REG_CMD    ( USER_PLUGIN_APB_BASE_ADDR + 0x10 )
#define UP_APB_REG_STATUS ( USER_PLUGIN_APB_BASE_ADDR + 0x14 )

#define SHA256_REG_MESSAGE ( USER_PLUGIN_APB_BASE_ADDR + 0x30 )
#define SHA256_REG_OUT0   ( USER_PLUGIN_APB_BASE_ADDR + 0x34 )
#define SHA256_REG_OUT1   ( USER_PLUGIN_APB_BASE_ADDR + 0x38 )
#define SHA256_REG_OUT2   ( USER_PLUGIN_APB_BASE_ADDR + 0x3c )
#define SHA256_REG_OUT3   ( USER_PLUGIN_APB_BASE_ADDR + 0x40 )
#define SHA256_REG_OUT4   ( USER_PLUGIN_APB_BASE_ADDR + 0x44 )
#define SHA256_REG_OUT5   ( USER_PLUGIN_APB_BASE_ADDR + 0x48 )
#define SHA256_REG_OUT6   ( USER_PLUGIN_APB_BASE_ADDR + 0x4c )
#define SHA256_REG_OUT7   ( USER_PLUGIN_APB_BASE_ADDR + 0x50 )


